# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "6.2.3"

image:
  repository: "quay.io/pires/docker-elasticsearch-kubernetes"
  tag: "6.2.3"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch"
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"

client:
  name: client
  replicas: 2
  serviceType: ClusterIP
  heapSize: "512m"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo

master:
  name: master
  replicas: 3
  heapSize: "512m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "4Gi"
    # storageClass: "ssd"
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "25m"
      memory: "512Mi"

  ## (dict) If specified, apply these annotations to each master Pod
  # podAnnotations:
  #   example: master-foo

data:
  name: data
  replicas: 2
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "300Gi"
    # storageClass: "ssd"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "soft"
  resources:
    limits:
      cpu: "2"
      memory: "16Gi"
    requests:
      cpu: "25m"
      memory: "1536Mi"

  ## (dict) If specified, apply these annotations to each data Pod
  # podAnnotations:
  #   example: data-foo

## Install Default RBAC roles and bindings
rbac:
  create: false
